// <auto-generated />
// Generated from Game.menutool. Edit the .menutool asset, not this file.

public static partial class MenuTool
{
    public static partial class Game
    {
        public const string Label = "Game";
        public const string Path = "Game";
        public const string DefaultFileName = "Default";

        public static partial class BasicSettings
        {
            public const string Label = "Basic Settings";
            public const string FileName = "Default";
            public const string Path = "Game/Basic Settings";

            public static partial class AudioManagerConfigs
            {
                public const string Label = "Audio Manager Configs";
                public const string FileName = "DefaultAudioManagerConfigs";
                public const string Path = "Game/Basic Settings/Audio Manager Configs";
            }

            public static partial class AudioClipData
            {
                public const string Label = "AudioClip Data";
                public const string FileName = "GenericAudioClipData";
                public const string Path = "Game/Basic Settings/AudioClip Data";
            }

            public static partial class SceneSwitchConfigs
            {
                public const string Label = "Scene Switch Configs";
                public const string FileName = "DefaultSceneSwitchConfigs";
                public const string Path = "Game/Basic Settings/Scene Switch Configs";
            }
        }
    }
}
