// <auto-generated />
// Generated from Game.menutool. Edit the .menutool asset, not this file.

public static partial class MenuTool
{
    public static partial class Game
    {
        public const string Label = "Game";
        public const string Path = "Game";
        public const string DefaultFileName = "Default";

        public static partial class BasicSettings
        {
            public const string Label = "Basic Settings";
            public const string FileName = "Default";
            public const string Path = "Game/Basic Settings";
        }

        public static partial class Configs
        {
            public const string Label = "Configs";
            public const string FileName = "Config";
            public const string Path = "Game/Configs";

            public static partial class Input
            {
                public const string Label = "Input";
                public const string FileName = "InputConfig";
                public const string Path = "Game/Configs/Input";
            }
        }

        public static partial class Distributables
        {
            public const string Label = "Distributables";
            public const string FileName = "Distribution";
            public const string Path = "Game/Distributables";
        }
    }
}
